frontend/app/models/field.py
from geoalchemy2.shape import to_shape
from sqlalchemy.sql.expression import select
from app import app
from sqlalchemy_serializer import SerializerMixin
from geoalchemy2.elements import WKBElement
from sqlalchemy.sql.schema import Column, ForeignKey
from sqlalchemy.sql.sqltypes import Integer, Text
from sqlalchemy.orm import relationship, column_property
import sqlalchemy

from .fieldlayer import FieldLayer

Base = app.DB.Model


class Field(Base, SerializerMixin):
    """Field consisting of two anchor Portals and multiple FieldLayers."""
    __tablename__ = 'field'

    serialize_types = (
        (WKBElement, lambda x: to_shape(x).to_wkt()),
    )

    serialize_rules = (
        ('-layers.field'),
    )

    id = Column(Integer, primary_key=True)

    title = Column(Text, nullable=False)

    # First anchor portal
    anchor_a_guid = Column(Text, ForeignKey(
        'portal.ingress_guid'), nullable=False)
    anchor_a = relationship('Portal', foreign_keys='Field.anchor_a_guid')

    # Second anchor portal
    anchor_b_guid = Column(Text, ForeignKey(
        'portal.ingress_guid'), nullable=False)
    anchor_b = relationship('Portal', foreign_keys='Field.anchor_b_guid')

    # Layers belonging to this field
    layers = relationship('FieldLayer', viewonly=True)

    maxOrder = column_property(
        select(sqlalchemy.func.max(FieldLayer.order)).where(
            FieldLayer.field_id == id).scalar_subquery()
    )

    def __repr__(self) -> str:
        return f'<Field #{self.id}: ({self.anchor_a_guid}, {self.anchor_b_guid})>'

frontend/app/views/fields.py
from flask import (Blueprint, render_template, request, abort, make_response,
                   jsonify, make_response, flash, redirect, url_for)
import shapely

import sqlalchemy
from sqlalchemy import and_
from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm.exc import NoResultFound

from geoalchemy2.shape import to_shape

from shapely.geometry import mapping

import geojson

from app import app
from app.models import Portal, Field, FieldLayer

bp = Blueprint('fields', __name__, url_prefix='/fields')


@bp.route('/')
def index():
    return render_template('fields/index.html', current_page='index')


@bp.route('/<int:id>.html', methods=['GET'])
def view(id):
    try:
        field = Field.query.where(Field.id == id).one()

    except NoResultFound as e:
        flash(f'Field #{id} not found.', 'danger')
        return redirect(url_for('fields.index'))

    return render_template('fields/view.html', field=field.to_dict())


@bp.route('/<int:id>.geojson', methods=['GET'])
def view_geojson(id):
    try:
        field = Field.query.where(Field.id == id).one()

        def portalFeature(portal, portalType):
            s = to_shape(portal.location)
            f = geojson.Feature(geometry=s, properties={
                'title': portal.title
            })
            return f

        def layerFeature(layer):
            g = shapely.wkt.loads(layer.polygon)
            f = geojson.Feature(geometry=g, properties={
                'order': layer.order,
                'title': layer.portal.title,
                'area': layer.area,
            })
            return f

        layerQuery = FieldLayer.query.where(FieldLayer.field_id == id) \
            .order_by(FieldLayer.order.asc())
        layers = layerQuery.all()

        portalFeatures = list(map(lambda x: portalFeature(x.portal, 'Layer'),
                                  layers))
        portalFeatures.append(portalFeature(field.anchor_a, 'Anchor'))
        portalFeatures.append(portalFeature(field.anchor_b, 'Anchor'))

        layerFeatures = list(map(layerFeature, layers))

        return geojson.FeatureCollection(portalFeatures+layerFeatures)

    except NoResultFound as e:
        abort(404)


@bp.route('/create', methods=['GET', 'POST'])
def create():
    if request.method == 'POST':
        with app.DB.session.begin() as tx:
            for k in ['anchor_a_guid', 'anchor_b_guid', 'title']:
                if not k in request.form or request.form[k] == '':
                    flash(f'Missing parameter: <em>{k}</em>', 'danger')
                    return redirect(url_for('fields.create'))

            guid_a = request.form['anchor_a_guid']
            guid_b = request.form['anchor_b_guid']

            if guid_a == guid_b:
                flash(
                    f'Portal Anchors cannot have the same GUID: <em>{guid_a}</em>', 'danger')
                return redirect(url_for('fields.create'))

            def _portal_from_guid(guid):
                try:
                    portal = Portal.query.where(
                        Portal.ingress_guid == guid).one()
                    return portal

                except sqlalchemy.orm.exc.NoResultFound as e:
                    flash(
                        f'Failed to get Portal object for GUID {guid}', 'danger')
                    return None

            title = request.form['title']
            portal_a = _portal_from_guid(guid_a)
            portal_b = _portal_from_guid(guid_b)

            if portal_a is None or portal_b is None:
                return redirect(url_for('fields.create'))

            try:
                field = Field(anchor_a_guid=guid_a,
                              anchor_b_guid=guid_b,
                              title=title)

                app.DB.session.add(field)

                flash(f'Field <em>{ title }</em> created.', 'success')
                return redirect(url_for('fields.index'))

            except Exception as e:
                flash(
                    f'Exception while creating field object! {str(e)}', 'danger')

    return render_template('fields/create.html', current_page='create')


@bp.route('/<int:id>/delete', methods=['POST'])
def delete(id):
    try:
        with app.DB.session.begin() as tx:
            field = Field.query.where(Field.id == id).one()
            title = field.title

            layers = FieldLayer.query.where(FieldLayer.field_id == id)
            layers.delete()

            app.DB.session.delete(field)

        flash(f'Field <em>{title}</em> deleted.', 'success')

    except IntegrityError as e:
        flash(f'Database error while deleting Field #{id}', 'danger')

    return redirect(url_for('fields.index'))


@bp.route('/<int:id>/update_title', methods=['POST'])
def update_title(id):
    if not 'title' in request.form:
        return jsonify({'success': False,
                        'message': 'Missing title parameter!'})

    try:
        with app.DB.session.begin() as tx:
            field = Field.query.where(Field.id == id).one()

            if field.title != request.form['title']:
                field.title = request.form['title']

        return jsonify({'success': True,
                        'title': request.form['title']})

    except NoResultFound as e:
        return jsonify({'success': False,
                        'message': f'SQL error: {e.orig}'})


@bp.route('/<int:id>/layers/add', methods=['POST'])
def add_layer(id):
    # Make sure all form parameters are present
    for k in ['layer_portal', 'layer_portal_guid', 'order']:
        if not k in request.form or request.form[k] is None:
            flash(f'Missing parameter {k} in form!', 'danger')
            return redirect(url_for('fields.view', id=id))

    guid = request.form['layer_portal_guid']

    try:
        with app.DB.session.begin() as tx:
            field = Field.query.where(Field.id == id).one()

            if field.anchor_a.ingress_guid == guid or field.anchor_b.ingress_guid == guid:
                flash(f'Layer portal can not be one of the anchors!', 'warning')
                return redirect(url_for('fields.view', id=id))

            layerCount = app.DB.session.query(sqlalchemy.func.count(FieldLayer.id)) \
                .where(and_(FieldLayer.field_id == field.id,
                            FieldLayer.guid == guid)) \
                .scalar()
            if layerCount > 0:
                flash(f'Layer already exists for field <em>{field.title}</em>')
                return redirect(url_for('fields.view', id=id))

            layer = FieldLayer(field_id=id,
                               guid=guid,
                               order=request.form['order'])

            app.DB.session.add(layer)
            flash(
                f'''Added layer <em>{request.form['layer_portal']}</em> to field.''', 'success')

    except NoResultFound as e:
        abort(404)

    return redirect(url_for('fields.view', id=id))


@bp.route('/<int:field_id>/layers/<int:layer_id>/delete', methods=['POST'])
def delete_layer(field_id, layer_id):
    try:
        with app.DB.session.begin() as tx:
            layerQuery = FieldLayer.query.where(FieldLayer.id == layer_id)
            layer = layerQuery.one()
            title = layer.portal.title

            layerQuery.delete()

        flash(f'Removed <em>{title}</em> from field.', 'success')

    except NoResultFound as e:
        flash('Failed to remove layer.', 'danger')

    return redirect(url_for('fields.view', id=field_id))


@bp.route('/ajax/search_portal', methods=['POST'])
def ajax_search_portal():
    if not 'q' in request.form or request.form['q'] is None:
        return '[]'

    searchString = request.form['q']

    portals = Portal.query.filter(Portal.title.like(
        f'%{searchString}%')).order_by(Portal.title.asc()).all()
    portals_serialized = []
    for portal in portals:
        portals_serialized.append({
            'guid': portal.ingress_guid,
            'title': portal.title,
            'image': portal.image
        })

    response = make_response(jsonify(portals_serialized))

    return response


@bp.route('/ajax/list_fields', methods=['GET'])
def ajax_list_fields():
    fields = Field.query.all()
    fields_serialized = list(map(lambda f: f.to_dict(), fields))
    return jsonify(fields_serialized)


@ bp.route('/ajax/<int:id>/layers', methods=['GET'])
def ajax_list_layers(id):
    layers = FieldLayer.query.where(FieldLayer.field_id == id).order_by(
        FieldLayer.order.asc()).all()
    layers_serialized = list(map(lambda x: x.to_dict(), layers))

    return jsonify(layers_serialized)


@bp.route('/ajax/<int:field_id>/<int:layer_id>/order_inc')
def ajax_layer_order_inc(field_id, layer_id):
    try:
        with app.DB.session.begin() as tx:
            layer = FieldLayer.query.where(and_(FieldLayer.id == layer_id,
                                                FieldLayer.field_id == field_id)).one()
            layer.order += 1

        return jsonify({'success': True,
                        'message': 'Layer order updated.'})

    except NoResultFound as e:
        return jsonify({'success': False,
                        'message': f'FieldLayer {field_id}/{layer_id} not found!'})


@bp.route('/ajax/<int:field_id>/<int:layer_id>/order_dec')
def ajax_layer_order_dec(field_id, layer_id):
    try:
        with app.DB.session.begin() as tx:
            layer = FieldLayer.query.where(and_(FieldLayer.id == layer_id,
                                                FieldLayer.field_id == field_id)).one()
            if layer.order < 1:
                return jsonify({'success': False,
                                'message': 'FieldLayer cannot have negative order!'})
            layer.order -= 1

        return jsonify({'success': True,
                        'message': 'Layer order updated.'})

    except NoResultFound as e:
        return jsonify({'success': False,
                        'message': f'FieldLayer {field_id}/{layer_id} not found!'})

frontend/app/templates/fields/create.html
{% extends 'base.html' %}
{% block title %}
Portals
{% endblock %}

{% block header %}
<h1>Fields</h1>
{% endblock %}

{% block content %}
<div class="row">
    {% include 'fields/navigation.html' %}

    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
        <div
            class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">Create new Field</h1>
        </div>
        <div class="container-fluid">
            <form action="{{ url_for('fields.create') }}" method="POST">
                <div class="row">
                    <div class="col-2">
                        <label for="title" class="form-label">Title</label>
                    </div>
                    <div class="col-10">
                        <input type="text" name="title" id="title" class="form-control" placeholder="Operation name" />
                    </div>
                </div>

                {% import 'portals/guid-search.html' as guid_search %}

                <div class="row">
                    <div class="col-2">1st Anchor</div>
                    <div class="col-5">
                        {{ guid_search.name_entry('anchor_a') }}
                    </div>
                    <div class="col-5">
                        {{ guid_search.guid_input('anchor_a') }}
                    </div>
                    {{ guid_search.script_block('anchor_a') }}
                </div>

                <div class="row">
                    <div class="col-2">2nd Anchor</div>
                    <div class="col-5">
                        {{ guid_search.name_entry('anchor_b') }}
                    </div>
                    <div class="col-5">
                        {{ guid_search.guid_input('anchor_b') }}
                    </div>
                    {{ guid_search.script_block('anchor_b') }}
                </div>

                <div class="form-group row">
                    <div class="col-4"></div>
                    <div class="col-4">
                        <button type="submit" class="btn btn-success form-control">Create Field</button>
                    </div>
                    <div class="col-4"></div>
                </div>
            </form>
        </div>
    </main>
</div>
{% endblock %}

frontend/app/templates/fields/index.html
{% extends 'base.html' %}
{% block title %}
Portals
{% endblock %}

{% block header %}
<h1>Fields</h1>
{% endblock %}

{% block content %}
<div class="row">
    {% include 'fields/navigation.html' %}

    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
        <div
            class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">Overview</h1>
        </div>
        <table class="table-responsive">
            <table id="fieldListing" class="table table-sm table-hover">
                <thead>
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Title</th>
                        <th scope="col">Layers</th>
                        <th scope="col">Actions</th>
                    </tr>
                </thead>
                <tbody>

                </tbody>
                <tfoot>
                    <th scope="col">ID</th>
                    <th scope="col">Title</th>
                    <th scope="col">Layers</th>
                    <th scope="col">Actions</th>
                </tfoot>
            </table>
            <script>
                const renderTitle = function (data, type, row) {
                    if (type == 'display') {
                        return `<a href="${row.id}.html">${row.title}</a>`;
                    }

                    return data;
                };

                const renderLayers = function (data, type, row) {
                    if (type == 'display') {
                        return data.length;
                    }

                    return data;
                };

                const renderActions = function (data, type, row) {
                    if (type == 'display') {
                        var infoLink = `<a href="${row.id}.html"><i class="bi-info-circle-fill"></i></a>`;
                        var deleteLink = `<a href="#" class="link-danger" 
                        title="Delete" data-bs-toggle="modal" data-bs-target="#modal-delete-${row.id}" 
                        aria-labelledby="modal-delete-${row.id}-label" 
                        aria-hidden="true"><i class="bi-trash"></i></a>`;

                        var deleteModal = `<div class="modal fade" id="modal-delete-${row.id}" tabindex="-1"
                aria-labelledby="modal-delete-${row.id}-label" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="modal-delete-${row.id}-label">Delete Field</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            Are you sure you want to delete the field <em>${row.title}</em>?
                        </div>
                        <div class="modal-footer">
                            <form action="/fields/${row.id}/delete" method="POST">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>
                                <button type="submit" class="btn btn-primary">Yes</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>`;

                        return infoLink + deleteLink + ' ' + deleteModal;
                    }

                    return data;
                };
                var fieldListingTable = $('#fieldListing').DataTable({
                    'ajax': {
                        'url': "{{ url_for('fields.ajax_list_fields') }}",
                        dataSrc: ''
                    },
                    'columns': [
                        {
                            data: 'id',
                            orderable: false,
                            className: 'text-center'
                        },
                        {
                            data: 'title',
                            orderable: true,
                            render: renderTitle
                        },
                        {
                            data: 'layers',
                            render: renderLayers,
                            className: 'text-center'
                        },
                        {
                            data: null,
                            render: renderActions,
                            className: 'text-center'
                        }
                    ]
                });
            </script>
        </table>
        <pre>{{ fields_json }}</pre>
    </main>
</div>
{% endblock %}

frontend/app/templates/fields/navigation.html
<nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
    <div class="position-sticky pt-3">
        <ul class="nav flex-column">
            <li class="nav-item">
                <a class="nav-link link-primary" href="{{ url_for('fields.index') }}">
                    <i class="fas fa-table"></i> Overview
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link link-success" href="{{ url_for('fields.create') }}">
                    <i class="fas fa-plus-square"></i> Create
                </a>
            </li>
        </ul>
    </div>
</nav>