frontend/app/views/admin.py
from app.rbac.decorators import roles_required
from flask import Blueprint, render_template

bp = Blueprint('admin', __name__, url_prefix='/admin')


@bp.route('/')
@roles_required(['Site Admin'])
def index():
    return render_template('admin/index.html')

frontend/app/templates/base.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>{% block title %}{% endblock %}</title>

    <!-- JQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

    <!-- Bootstrap / Bootswatch -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootswatch@5.1.0/dist/journal/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj"
        crossorigin="anonymous"></script>

    <!-- Bootstrap Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css"
        integrity="sha384-tKLJeE1ALTUwtXlaGjJYM3sejfssWdAaWR2s97axw4xkiAdMzQjtOjgcyw0Y50KU" crossorigin="anonymous">

    <!-- Datatables -->
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.0/css/dataTables.bootstrap5.min.css" />
    <script src="https://cdn.datatables.net/1.11.0/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.11.0/js/dataTables.bootstrap5.min.js"></script>

    <!-- wellknown -->
    <script src="{{ url_for('static', filename='wellknown.js') }}"></script>

    <!-- jQuery Editable -->
    <script src="{{ url_for('static', filename='jquery-editable.js') }}"></script>

    <!-- jQuery Progressbar -->
    <script src="{{ url_for('static', filename='jquery-progress.js') }}"></script>

    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/80389496ec.js" crossorigin="anonymous"></script>

    <!-- Flask-JSGlue -->
    {{ JSGlue.include() }}

    <!-- Own CSS -->
    <link ref="stylesheet" href="{{ url_for('static', filename='style.css') }}" />
</head>

<body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <a class="navbar-brand" href="{{ url_for('index') }}">
            <i class="bi-map" /></i> Ingress GIS
            {% if g.current_user %}
            <small class="text-secondary">
                <a href="{{ url_for('rbac.user.my_profile') }}" class="nav-link">
                    {{ g.current_user.username }}
                </a>
            </small>
            {% endif %}
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main_navbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="main_navbar">
            <ul class="navbar-nav">
                <li class="nav-item">
                    {% if g.current_user %}
                    <a class="nav-link" href="{{ url_for('auth.login.logout') }}" title="Log out">
                        <i class="fas fa-sign-out-alt"></i>
                    </a>
                    {% else %}
                    <a class="nav-link" href="{{ url_for('auth.login.login') }}" title="Log in">
                        <i class="fas fa-sign-in-alt"></i>
                    </a>
                    {% endif %}
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('portals.index') }}" title="Portals">
                        <i class="fas fa-map-marker-alt"></i>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('fields.index') }}" title="Fields">
                        <i class="fas fa-layer-group"></i>
                    </a>
                </li>
                {% if rbac_has_role('Site Admin') %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('admin.index') }}" title="Admin Tools"><i
                            class="fa fa-tools"></i></a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <div class="container-fluid">
        <div class="header">
            {% block header %}{% endblock %}
        </div>

        {% for category, message in get_flashed_messages(with_categories=True) %}
        <div class="alert alert-{{ category }} alert-dismissible fade show" id="alert-{{ loop.index }}">
            <button type="button" class="btn btn-{{ category }} close" data-bs-dismiss="alert">&times;</button>
            {{ message | safe }}
        </div>
        {% if not category in ['danger', 'warning'] %}
        <script>
            window.setTimeout(function () {
                $('#alert-{{ loop.index }}').fadeTo(500, 0).slideUp(500, function () {
                    $(this).remove();
                })
            }, 5000);
        </script>
        {% endif %}
        {% endfor %}

        {% block content %}{% endblock %}
    </div>

    <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
        <small>Ingress GIS v0.0.5 / &copy; 2021 <a href="https://t.me/png85"
                class="text-decoration-none text-reset fw-bold">@png85</a></small>
    </div>
</body>

</html>

frontend/app/templates/index.html
{% extends 'base.html' %}
{% block title %}
Hello, Title
{% endblock %}

{% block header %}
<h1>Hello, header!</h1>
{% endblock %}

{% block content %}
{% if g.current_user %}
<pre>{{ g.current_user }}</pre>
{% endif %}
{% endblock %}