frontend/app/models/portal.py
from geoalchemy2.elements import WKBElement
from geoalchemy2.shape import to_shape
from geoalchemy2.types import Geometry
from sqlalchemy.sql.schema import Column
from sqlalchemy.sql.sqltypes import DateTime, Integer, Text
from sqlalchemy_serializer.serializer import SerializerMixin
from app import app

Base = app.DB.Model


class Portal(Base, SerializerMixin):
    """Record for a single Ingress portal"""
    __tablename__ = 'portal'

    serialize_types = (
        (WKBElement, lambda x: to_shape(x).to_wkt()),
    )

    id = Column(Integer, primary_key=True)

    ingress_guid = Column(Text, nullable=False, unique=True)
    intel_link = Column(Text, nullable=False)
    title = Column(Text, nullable=False)
    image = Column(Text)
    location = Column(Geometry(geometry_type='POINT', srid=4326))
    address = Column(Text, nullable=True)
    address_last_query = Column(DateTime, nullable=True)

    def __repr__(self) -> str:
        return f'<Portal #{self.id}: "{self.title}">'

frontend/app/views/portals.py
import datetime
from json.decoder import JSONDecodeError
from flask_sqlalchemy import SQLAlchemy
import sqlalchemy
from sqlalchemy import and_, or_
from sqlalchemy.orm.exc import NoResultFound
from sqlalchemy.exc import IntegrityError

from geoalchemy2.shape import to_shape

from shapely.geometry import mapping

from flask import (jsonify, abort, request, Blueprint, make_response, render_template,
                   url_for, redirect, flash)
from flask_cors import cross_origin

import json

from app import app
from app.models import Portal, Field, FieldLayer

from geopy import Nominatim

#
# Blueprints for URL matching
bp_rest = Blueprint('portals-rest', __name__, url_prefix='/api/portals')
bp = Blueprint('portals', __name__, url_prefix='/portals')


@bp_rest.route('/', methods=['GET'])
@cross_origin()
def rest_list_portals():
    portals = Portal.query.all()
    portals_serialized = list(map(lambda p: p.to_dict(), portals))

    return jsonify(portals_serialized)


def _deletePortal(guid):
    """Remove Portal from database

    Removes the portal with the given GUID including all Fields and Layers using this portal.

    Args:
        guid (string): Ingress GUID or the portal to remove

    Returns:
        bool: Boolean indicating whether removal was successful
    """
    try:
        with app.DB.session.begin() as tx:
            # Fetch Portal object to see if it's a valid GUID
            portalQuery = Portal.query.where(Portal.ingress_guid == guid)
            portal = portalQuery.one()

            # Delete all layers using this Portal
            layersUsingPortal = FieldLayer.query.where(FieldLayer.guid == guid)
            layersUsingPortal.delete()

            # Delete all fields using this Portal as an anchor
            fieldsUsingPortal = Field.query.where(or_(Field.anchor_a_guid == guid,
                                                      Field.anchor_b_guid == guid))
            for f in fieldsUsingPortal.all():
                layers = FieldLayer.query.where(
                    FieldLayer.field_id == Field.id)
                layers.delete()

            # Finally, remove Field records and the Portal itself
            fieldsUsingPortal.delete()
            portalQuery.delete()

    except NoResultFound as e:
        app.logger.error('Tried to delete portal with non-existant GUID: %s',
                         guid)
        return False

    except IntegrityError as e:
        app.logger.error('IntegrityError while deleting portal %s: %s',
                         guid, e.orig)
        return False

    return True


def _updatePortalFromJSON(guid, portal_json):
    for (k, check_null) in []:
        if not k in portal_json:
            return (False, False, f'Missing key in Portal JSON data: {k}')

        if check_null and not portal_json[k]:
            return (False, False, f'Value for JSON key "{k} can not be null')

    try:
        with app.DB.session.begin() as tx:
            newPortal = False
            try:
                portalQuery = Portal.query.where(Portal.ingress_guid == guid)
                portal = portalQuery.one()
            except NoResultFound as e:
                portal = Portal(ingress_guid=guid)
                newPortal = True

            if portal_json['image']:
                portal.image = portal_json['image']

            portal.title = portal_json['title']

            lat = portal_json['latE6'] / (10.0**6.0)
            lng = portal_json['lngE6'] / (10.0**6.0)
            portal.intel_link = f'https://intel.ingress.com/?pll={lat:.6f},{lng:.6f}'
            portal.location = f'POINT({lng:.6f} {lat:.6f})'

            if newPortal:
                app.DB.session.add(portal)

            return (True, newPortal, 'Portal data stored successfully.')

    except Exception as e:
        app.logger.error('Caught Exception while updating portal with GUID=%s: %s',
                         guid, str(e))
        return (False, False, 'Database error.')


@bp_rest.route('/bulk', methods=['PUT'])
@cross_origin()
def rest_bulk_update():
    if request.method == 'PUT':
        try:
            portals = json.loads(request.data)
            updateResults = {}
            guids = {
                'updated': [],
                'failed': []
            }

            for guid in portals:
                (successful,
                 isNewPortal,
                 message) = _updatePortalFromJSON(guid, portals[guid])

                if not successful:
                    updateResults[guid] = {'success': False,
                                           'message': message}
                    guids['failed'].append(guid)
                else:
                    updateResults[guid] = {'success': True,
                                           'is_new': isNewPortal,
                                           'message': message}
                    guids['updated'].append(guid)

            return jsonify({
                'guids': guids,
                'results': updateResults
            })

        except JSONDecodeError as e:
            app.logger.error(
                'Failed to parse bulk portal data: %s', request.data)
            return jsonify({
                'success': False,
                'message': 'Failed to parse portal data.',
                'raw_data': str(request.data)
            })

    return jsonify({
        'success': False,
        'message': 'Unsupported request method.'
    })


@bp_rest.route('/<string:guid>', methods=['GET', 'PUT', 'DELETE'])
@cross_origin()
def rest_portal_put(guid):
    #
    # HTTP PUT: Create or update portal record
    if request.method == 'PUT':
        try:
            #
            # Make sure all required properties are present in passed JSON object
            portal_json = json.loads(request.data)
            (success,
             newPortal,
             message) = _updatePortalFromJSON(guid, portal_json)

            return jsonify({
                'success': success,
                'is_new': newPortal,
                'message': message,
                'guid': guid
            })

        except json.decoder.JSONDecodeError as e:
            app.logger.error('Failed to parse portal JSON data: %s',
                             request.data)
            return make_response(jsonify({
                'success': False,
                'message': f'Failed to parse JSON data: "{request.data}"'
            }), 400)

    #
    # HTTP DELETE: Remove portal record
    elif request.method == 'DELETE':
        if _deletePortal(guid):
            return jsonify({'success': True})
        else:
            return jsonify({'success': False, 'message': 'Failed to remove portal from database.'})

    #
    # Default: Return data for given ingress GUID as JSON
    try:
        portal = Portal.query.filter(Portal.ingress_guid == guid).one()
        return jsonify(portal.to_dict())

    except NoResultFound as e:
        abort(404)


@bp.route('/')
def index():
    portals = Portal.query.all()
    return render_template('portals/index.html',
                           current_page='index',
                           portals=portals
                           )


@bp.route('/<int:id>.html', methods=['GET'])
def portal_by_id(id):
    try:
        portal = Portal.query.where(Portal.id == id).one()
        location = mapping(to_shape(portal.location))
        return render_template('portals/details.html', portal=portal, location=location)

    except NoResultFound:
        response = make_response('Portal not found!', 404)
        abort(response)


@bp.route('/<string:guid>/delete', methods=['POST'])
def delete(guid):
    if _deletePortal(guid):
        flash('Portal removed from database.', 'success')
    else:
        flash('Failed to remove portal from database!', 'danger')

    return redirect(url_for('portals.index'))


@bp.route('<string:guid>/ajax/fields.json')
def ajax_fields_for_portal(guid):
    try:
        fields = Field.query.where(or_(Field.anchor_a_guid == guid,
                                       Field.anchor_b_guid == guid)).all()
        fields_serialized = list(map(lambda x: x.to_dict(), fields))

        return jsonify(fields_serialized)

    except Exception as e:
        app.logger.error('Caught exception: %s', str(e))
        return jsonify([])


@bp.route('<string:guid>/ajax/layers.json')
def ajax_layers_for_portal(guid):
    try:
        layers = FieldLayer.query.where(FieldLayer.guid == guid).all()
        layers_serialized = list(map(lambda x: x.to_dict(), layers))

        return jsonify(layers_serialized)

    except Exception as e:
        app.logger.error('Caught exception: %s', str(e))
        return jsonify([])


@bp.route('/stats.html', methods=['GET'])
def stats():
    stats = {
    }

    try:
        portalCountQuery = app.DB.session.query(
            sqlalchemy.func.count(Portal.id))
        stats['portalCount'] = portalCountQuery.scalar()
    except Exception as e:
        app.logger.error('Exception while counting portals: %s', str(e))
        stats['portalCount'] = 0

    try:
        unusedCountQuery = app.DB.session.query(
            sqlalchemy.func.count(Portal.id)).filter(and_(Portal.usage_anchor == 0,
                                                          Portal.usage_layer == 0))
        stats['unusedCount'] = unusedCountQuery.scalar()
    except Exception as e:
        app.logger.error('Excepting while counting unused portals: %s', str(e))
        stats['unusedCount'] = 0

    return render_template('portals/stats.html',
                           stats=stats)


@bp.route('/scheduler-stats.html', methods=['GET'])
def scheduler_stats():
    return render_template('portals/scheduler-stats.html')


@bp.route('/prune', methods=['GET'])
def prune():
    guids = []
    with app.DB.session.begin() as tx:
        for portal in Portal.query.where(and_(Portal.usage_anchor == 0,
                                              Portal.usage_layer == 0)).all():

frontend/app/templates/portals/details.html
{% extends 'base.html' %}
{% block title %}
Portals
{% endblock %}

{% block header %}
<h1>Portal Database</h1>
{% endblock %}

{% block content %}
<div class="row">
    {% include 'portals/navigation.html' %}

    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
        <div
            class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">{{ portal.title }}</h1>
        </div>
        <div class="container">
            {% if portal.image != None %}
            <div class="row">
                <div class="text-center">
                    <img src="{{ portal.image }}" class="img-fluid rounded" alt="{{ portal.title }}" />
                </div>
            </div>
            {% endif %}
            <div class="row">
                <div class="col-2 h5">Location</div>
                <div class="col-8 text-center">{{ portal.location | to_wkt }}</div>
            </div>
            {% if portal.address != None %}
            <div class="row">
                <div class="col-2 h5">Address</div>
                <div class="col-8 text-center">{{ portal.address }}</div>
            </div>
            {% endif %}
            <div class="row">
                <div class="col-2 h5">Links</div>
                <div class="col-8 text-center">
                    <!-- Intel -->
                    <a href="{{ portal.intel_link }}" target="_new" title="Ingress Intel"><i class="bi-geo-alt"></i></a>

                    <!-- Google Maps-->
                    <a href="https://www.google.com/maps/search/?api=1&query={{ location.coordinates[1] }},{{ location.coordinates[0] }}"
                        title="Google Maps"> <i class="bi-map-fill"> </i></a>

                </div>
                <div class="col-2"></div>
            </div>
            <div class="row">
                <div class="col-6">
                    <nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='currentColor'/%3E%3C/svg%3E&#34;);"
                        aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{{ url_for('fields.index') }}">Fields</a></li>
                            <li class="breadcrumb-item">Anchors</li>
                            <li class="breadcrumb-item">{{ portal.title }}</li>
                        </ol>
                    </nav>
                </div>
                <div class="col-6">
                    <nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='currentColor'/%3E%3C/svg%3E&#34;);"
                        aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{{ url_for('fields.index') }}">Fields</a></li>
                            <li class="breadcrumb-item">Layers</li>
                            <li class="breadcrumb-item">{{ portal.title }}</li>
                        </ol>
                    </nav>
                </div>
                <!-- <div class="col-6 text-center h4">Fields: Anchor</div> -->
                <!-- <div class="col-6 text-center h4">Fields: Layer</div> -->
            </div>
            <div class="row">
                <div class="col-6">
                    <div class="table-responsive">
                        <table class="table table-sm table-hover" id="fieldUsageTable">
                            <thead>
                                <th scope="col">Title</th>
                                <th scope="col"></th>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                    <script>
                        $(document).ready(function () {
                            $dt = $('#fieldUsageTable');
                            $dt.DataTable({
                                'ajax': {
                                    'url': "{{ url_for('portals.ajax_fields_for_portal', guid=portal.ingress_guid) }}",
                                    dataSrc: ''
                                },
                                'columns': [
                                    {
                                        data: 'title',
                                        orderable: true
                                    },
                                    {
                                        data: null,
                                        orderable: false,
                                        className: 'text-center',
                                        render: function (data, type, row) {
                                            if (type == 'display') {
                                                return `<a href="../fields/${row.id}.html"><i class="bi-info-circle-fill"></i></a>`;
                                            }

                                            return '';
                                        }
                                    }
                                ],
                                'order': [[0, 'asc']],
                                'paging': true,
                                'searching': false,
                                'ordering': true,
                                'lengthMenu': [[10, 25, 50, -1], [10, 25, 50, "All"]]
                            });
                        });
                    </script>
                </div>
                <div class="col-6">
                    <div class="table-responsive">
                        <table class="table table-sm table-hover" id="layerUsageTable">
                            <thead>
                                <th scope="col">Title</th>
                                <th scope="col"></th>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                        <script>
                            $(document).ready(function () {
                                $dt = $('#layerUsageTable');
                                $dt.DataTable({
                                    'ajax': {
                                        'url': "{{ url_for('portals.ajax_layers_for_portal', guid=portal.ingress_guid) }}",
                                        dataSrc: ''
                                    },
                                    'columns': [
                                        {
                                            data: 'field.title',
                                            orderable: true,
                                            render: function (data, type, row) {
                                                if (type == 'display') {
                                                    return `<a href="../fields/${row.field.id}.html">${row.field.title}</a>`;
                                                }

                                                return data;
                                            }
                                        },
                                        {
                                            data: null,
                                            orderable: false,
                                            className: 'text-center',
                                            render: function (data, type, row) {
                                                if (type == 'display') {
                                                    return `<a href="../fields/${row.field.id}.html"><i class="bi-info-circle-fill"></i></a>`;
                                                }

                                                return '';
                                            }
                                        }
                                    ],
                                    'order': [[0, 'asc']],
                                    'paging': true,
                                    'searching': false,
                                    'ordering': true,
                                    'lengthMenu': [[10, 25, 50, -1], [10, 25, 50, "All"]]
                                });
                            });
                        </script>
                    </div>
                </div>
            </div>
        </div>
    </main>
</div>
{% endblock %}

frontend/app/templates/portals/index.html
{% extends 'base.html' %}
{% block title %}
Portals
{% endblock %}

{% block header %}
<h1>Portal Database</h1>
{% endblock %}

{% block content %}
<div class="row">
    {% include 'portals/navigation.html' %}

    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
        <div
            class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">Overview</h1>
        </div>

        <div class="table-responsive">
            <table id="portalListing" class="table table-sm table-hover">
                <thead>
                    <tr>
                        <th scope="col" class="text-center">ID</th>
                        <th scope="col" class="text-center">
                            <i class="bi-image" title="Image" title="Portal Image"></i>
                        </th>
                        <th scope="col">Title</th>
                        <th scope="col" class="text-center"><i class="bi-geo-alt" title="Intel Link"></i></th>
                        <th scope="col" class="text-center"><i class="bi-cone-striped" title="Used as Anchor"></i></th>
                        <th scope="col" class="text-center"><i class="bi-triangle" title="Used as Layer"></i></th>
                        <th scope="col">Location</th>
                        <th scope="col" class="text-center">Actions</th>
                    </tr>
                </thead>
                <tbody>

                </tbody>
                <tfoot>
                    <tr>
                        <th scope="col" class="text-center">ID</th>
                        <th scope="col" class="text-center">
                            <i class="bi-image" title="Image" title="Portal Image"></i>
                        </th>
                        <th scope="col">Title</th>
                        <th scope="col" class="text-center"><i class="bi-geo-alt" title="Intel Link"></i></th>
                        <th scope="col" class="text-center"><i class="bi-cone-striped" title="Used as Anchor"></i></th>
                        <th scope="col" class="text-center"><i class="bi-triangle" title="Used as Layer"></i></th>
                        <th scope="col">Location</th>
                        <th scope="col" class="text-center">Actions</th>
                    </tr>
                </tfoot>
            </table>
            {% for portal in portals %}
            <div class="modal fade" id="modal-delete-{{ portal.id }}" tabindex="-1"
                aria-labelledby="modal-delete-{{ portal.id }}-label" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="modal-delete-{{ portal.id }}-label">Delete Portal</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            Are you sure you want to delete the portal <em>{{ portal.title }}</em>?
                        </div>
                        <div class="modal-footer">
                            <form action="{{ url_for('portals.delete', guid=portal.ingress_guid) }}" method="POST">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>
                                <button type="submit" class="btn btn-primary">Yes</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
            <script src="{{ url_for('static', filename='portals/portal-listing-table.js') }}"></script>
            <script>
                $(document).ready(function () {
                    var portalListingTable = $('#portalListing').DataTable({
                        'ajax': {
                            url: "{{ url_for('portals-rest.rest_list_portals') }}",
                            dataSrc: ''
                        },
                        'columns': [
                            {
                                data: 'id',
                                render: renderPortalIDs,
                                orderable: false,
                                className: 'text-center align-middle',
                                searchable: false
                            },
                            {
                                data: 'image',
                                render: renderPortalImage,
                                defaultContent: '',
                                className: 'text-center align-middle',
                                orderable: false,
                                searchable: false
                            },
                            {
                                data: 'title',
                                orderable: true,
                                className: 'align-middle',
                                searchable: true,
                                render: function (data, type, row) {
                                    if (type == 'display') {
                                        var html = `<a href="${row.id}.html" title="`
                                            + (row.address != null ? row.address : '')
                                            + `">${row.title}</a>`;

                                        return html;
                                    }

                                    return data;
                                }
                            },
                            {
                                data: 'intel_link',
                                render: renderIntelLink,
                                className: 'text-center align-middle',
                                orderable: false,
                                searchable: false
                            },
                            {
                                data: 'usage_anchor',
                                orderable: false,
                                searchable: false,
                                className: 'text-center align-middle'
                            },
                            {
                                data: 'usage_layer',
                                orderable: false,
                                searchable: false,
                                className: 'text-center align-middle'
                            },
                            {
                                data: 'location',
                                orderable: false,
                                render: renderLocation,
                                className: 'text-center align-middle',
                                searchable: false
                            },
                            {
                                data: 'null',
                                orderable: false,
                                className: 'text-center align-middle',
                                render: renderActions,
                                searchable: false
                            }
                        ],
                        'order': [[2, "asc"]]
                    });
                });
            </script>
        </div>
    </main>
</div>
{% endblock %}

frontend/app/templates/portals/navigation.html
<nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
    <div class="position-sticky pt-3">
        <ul class="nav flex-column">
            <li class="nav-item {{ 'active' if current_page == 'index' }}">
                <a class="nav-link" href="{{ url_for('portals.index') }}">
                    <i class="fas fa-search-location"></i> Overview
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('portals.stats') }}">
                    <i class="fas fa-database"></i> Statistics
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('portals.scheduler_stats') }}">
                    <i class="fa fa-clock"></i> Scheduler
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('static', filename='iitc-ingress-gis.user.js') }}">
                    <i class="fas fa-file-code"></i> IITC Plugin
                </a>
            </li>
        </ul>
    </div>
</nav>

frontend/app/templates/portals/stats.html
{% extends 'base.html' %}
{% block title %}
Portals
{% endblock %}

{% block header %}
<h1>Portal Database</h1>
{% endblock %}

{% block content %}
<div class="row">
    {% include 'portals/navigation.html' %}

    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
        <div
            class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2" id="field-title" data-bs-toggle="tooltip" title="Double-click to edit">Statistics</h1>
        </div>
        <div class="container-fluid">
            <div class="row">
                <div class="col-2">Total Portal Count</div>
                <div class="col-4 text-center">{{ stats.portalCount }}</div>
                <div class="col-2">Unused</div>
                <div class="col-4 text-center">
                    {{ stats.unusedCount }}
                    <a href="{{ url_for('portals.prune') }}" title="Prune unused portals"><i
                            class="fas fa-trash-alt"></i></a>
                </div>
            </div>
            <div class="row">
                <div class="col-2">Witohut Address</div>
                <div class="col-4 text-center"><span id="portals-without-address"></span></div>
            </div>
        </div>
        <script>
            function fetchPortalsWithoutAddress() {
                $.get("{{ url_for('portals.portals_without_address') }}", function (data, textStatus, jqXHR) {
                    $('#portals-without-address').html(data.count);
                }, 'json');
            }

            $(document).ready(function () {
                fetchPortalsWithoutAddress();
                setInterval(fetchPortalsWithoutAddress, 5000);
            });
        </script>
    </main>
</div>
{% endblock %}